# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EncryptDecryptComponent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EncryptDecryptComponent

  target 'EncryptDecryptComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EncryptDecryptComponentUITests' do
    # Pods for testing
  end

pod 'CryptoSwift'

end
