# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSToastLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSToastLib

  target 'IOSToastLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSToastLibUITests' do
    # Pods for testing
  end

end
